//! `persistence` — the Mode-1 content-addressed save (ADR-0033).
//!
//! [`save_world`] reads the authoritative ECS state (read-only, `Owner`-filtered),
//! encodes it as a postcard [`SaveBlob`], and returns its blake3 [`ContentId`]
//! (ADR-0032). [`load_world`] reconstructs an EQUIVALENT world through
//! `engine_core::spawn_owned` (the sole sim-entity construction path).
//! [`load_world_verified`] enforces the id at the store boundary.
//!
//! Design: the blob is a **DTO mirror** of the engine-core components — this
//! crate owns the `Serialize`/`Deserialize`, so `engine-core` stays
//! `protocol`+`bevy_ecs`-only (the same isolation `protocol::StateEntry` gives
//! the wire format). Only AUTHORITATIVE state is persisted (`Owner`, `Position`,
//! `Velocity`, `Contacts`, + the `Tick`/`LocalPeer` resources); render/interp/
//! input state is derived and regenerated by the schedule, `Interactable` is
//! content-authored, and `Health` lives in the (unconsumed) `scripting` crate —
//! all excluded.
//!
//! The content id is order-independent: entity records are sorted into a
//! canonical order before hashing, so the id depends only on the SET of entity
//! states, not spawn order. Durable stores are B3 (native `FileStore`) / B4
//! (browser `IdbStore`); this crate ships the in-memory [`MemoryStore`].

use std::collections::HashMap;
use std::fmt;

use bevy_ecs::entity::Entity;
use bevy_ecs::world::World;
use engine_core::{Contacts, LocalPeer, Owner, Position, Tick, Velocity, insert_sim, spawn_owned};
use protocol::{ContentId, PeerId, VersionTriple, content_id};
use serde::{Deserialize, Serialize};

/// Save-blob schema version, checked on load. Independent of
/// `protocol::WIRE_VERSION` — this is the SAVE format's version. Bump on any
/// [`SaveBlob`] shape change.
pub const SAVE_VERSION: u8 = 1;

/// A serialized Mode-1 world: sim metadata + the authoritative entity set.
/// `version` is the FIRST field (postcard has no envelope, so it is effectively
/// the leading version byte — mirrors `protocol`'s codec convention).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct SaveBlob {
    /// [`SAVE_VERSION`] at encode time.
    pub version: u8,
    /// Reserved `{engine, content, schema}` triple (ADR-0032); `None` today —
    /// Phase 5 enforces it at session join.
    pub triple: Option<VersionTriple>,
    /// The authoritative sim tick.
    pub tick: u64,
    /// Who "I" am (every entity is owned by this peer in a Mode-1 save).
    pub local: PeerId,
    /// The authoritative entities, in canonical (encoding-sorted) order.
    pub entities: Vec<EntityRecord>,
}

/// One saved entity's authoritative state (a DTO mirror of the engine-core
/// components). `contacts` is `None` when the entity carries no [`Contacts`].
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
pub struct EntityRecord {
    pub owner: PeerId,
    pub pos: Vec2Record,
    pub vel: Vec2Record,
    pub contacts: Option<u32>,
}

/// A 2D vector DTO (mirrors `engine_core::Position`/`Velocity`). Raw `f32` — a
/// local save is not bandwidth-bound, so no quantization; postcard encodes each
/// as 4 fixed LE bytes, so the encoding is deterministic.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
pub struct Vec2Record {
    pub x: f32,
    pub y: f32,
}

/// Errors from [`save_world`] / [`load_world`] / [`load_world_verified`].
#[derive(Debug)]
pub enum SaveError {
    /// postcard encode/decode failure.
    Codec(postcard::Error),
    /// The blob's [`SaveBlob::version`] does not match [`SAVE_VERSION`].
    VersionMismatch { got: u8 },
    /// A verified load was handed a blob whose content id ≠ the claimed id.
    ContentMismatch { expected: ContentId, got: ContentId },
    /// The world lacks a resource a save requires (`Tick` / `LocalPeer`).
    MissingResource(&'static str),
}

impl fmt::Display for SaveError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SaveError::Codec(e) => write!(f, "save codec error: {e}"),
            SaveError::VersionMismatch { got } => {
                write!(f, "save version mismatch: got {got}, want {SAVE_VERSION}")
            }
            SaveError::ContentMismatch { expected, got } => {
                write!(f, "content id mismatch: expected {expected}, got {got}")
            }
            SaveError::MissingResource(r) => write!(f, "world missing resource for save: {r}"),
        }
    }
}

impl std::error::Error for SaveError {}

impl From<postcard::Error> for SaveError {
    fn from(e: postcard::Error) -> Self {
        SaveError::Codec(e)
    }
}

/// Serialize the authoritative world state and return its content id + blob.
/// Read-only: iterates entities via `&World`, keeping only `Owner`-bearing sim
/// entities (bevy_ecs 0.19 stores resources on entities — the `Owner` filter
/// excludes those). The record set is sorted into a canonical order so the id is
/// independent of spawn order.
pub fn save_world(world: &World) -> Result<(ContentId, Vec<u8>), SaveError> {
    // Read the required resources first, so a world missing one fails fast
    // (before the entity walk + sort).
    let tick = world
        .get_resource::<Tick>()
        .ok_or(SaveError::MissingResource("Tick"))?
        .0;
    let local = world
        .get_resource::<LocalPeer>()
        .ok_or(SaveError::MissingResource("LocalPeer"))?
        .0;

    // Every `Owner`-bearing entity also has `Position` + `Velocity`: `spawn_owned`
    // (the sole sim-entity construction path) attaches all three together, so the
    // `?` early-returns here never silently drop a real sim entity.
    let records: Vec<EntityRecord> = world
        .iter_entities()
        .filter_map(|e| {
            let owner = e.get::<Owner>()?.0;
            let pos = e.get::<Position>()?;
            let vel = e.get::<Velocity>()?;
            let contacts = e.get::<Contacts>().map(|c| c.0);
            Some(EntityRecord {
                owner,
                pos: Vec2Record { x: pos.x, y: pos.y },
                vel: Vec2Record { x: vel.x, y: vel.y },
                contacts,
            })
        })
        .collect();

    // Canonical order: sort by each record's postcard encoding — a deterministic
    // TOTAL order (f32 is not `Ord`, so we cannot sort on the values directly).
    // Pre-encode once, propagating any codec error (no unwrap). Two records with
    // identical state are indistinguishable — correct for content-addressing.
    let mut keyed: Vec<(Vec<u8>, EntityRecord)> = Vec::with_capacity(records.len());
    for rec in records {
        keyed.push((postcard::to_stdvec(&rec)?, rec));
    }
    keyed.sort_by(|a, b| a.0.cmp(&b.0));
    let entities: Vec<EntityRecord> = keyed.into_iter().map(|(_, rec)| rec).collect();

    let blob = SaveBlob {
        version: SAVE_VERSION,
        triple: None,
        tick,
        local,
        entities,
    };
    let bytes = postcard::to_stdvec(&blob)?;
    let id = content_id(&bytes);
    Ok((id, bytes))
}

/// Reconstruct an equivalent world from a save blob, returning its content id.
/// Clears existing sim entities, reseeds the sim (`insert_sim` + the saved
/// `Tick`), and rebuilds every entity through `spawn_owned` (the sole
/// construction path). `dt` is runtime config (the fixed timestep), NOT saved
/// state. Does not verify the id — see [`load_world_verified`].
pub fn load_world(world: &mut World, blob: &[u8], dt: f32) -> Result<ContentId, SaveError> {
    let id = content_id(blob);
    let parsed: SaveBlob = postcard::from_bytes(blob)?;
    if parsed.version != SAVE_VERSION {
        return Err(SaveError::VersionMismatch {
            got: parsed.version,
        });
    }

    // Two-pass clear: `iter_entities` borrows `&World`, `despawn` needs `&mut` —
    // collect the ids first, then despawn.
    let existing: Vec<Entity> = world
        .iter_entities()
        .filter(|e| e.get::<Owner>().is_some())
        .map(|e| e.id())
        .collect();
    for e in existing {
        world.despawn(e);
    }

    insert_sim(world, parsed.local, dt);
    world.insert_resource(Tick(parsed.tick));

    for rec in &parsed.entities {
        let e = spawn_owned(
            world,
            rec.owner,
            Position {
                x: rec.pos.x,
                y: rec.pos.y,
            },
            Velocity {
                x: rec.vel.x,
                y: rec.vel.y,
            },
        );
        if let Some(c) = rec.contacts {
            world.entity_mut(e).insert(Contacts(c));
        }
    }
    Ok(id)
}

/// Like [`load_world`], but first assert the blob hashes to `id` (the
/// content-addressing guarantee) — a store returning the wrong/corrupt bytes for
/// a key is caught here, before any world mutation.
pub fn load_world_verified(
    world: &mut World,
    id: ContentId,
    blob: &[u8],
    dt: f32,
) -> Result<(), SaveError> {
    let got = content_id(blob);
    if got != id {
        return Err(SaveError::ContentMismatch { expected: id, got });
    }
    load_world(world, blob, dt)?;
    Ok(())
}

/// A content-addressed blob store: `put` keys a blob by its own content id
/// (idempotent — identical content dedupes), `get` fetches by id.
pub trait ContentStore {
    /// Store `blob` under its content id and return that id.
    fn put(&mut self, blob: Vec<u8>) -> ContentId;
    /// Fetch the blob for `id`, or `None` if absent (treat as a cache miss).
    fn get(&self, id: ContentId) -> Option<Vec<u8>>;
    /// Whether `id` is present.
    fn contains(&self, id: ContentId) -> bool {
        self.get(id).is_some()
    }
}

/// In-memory [`ContentStore`] — the wasm-safe acceptance vehicle (in-session
/// save/reload). Durable stores are B3 (native file) / B4 (browser IndexedDB).
#[derive(Default)]
pub struct MemoryStore(HashMap<ContentId, Vec<u8>>);

impl MemoryStore {
    /// A new, empty store.
    pub fn new() -> Self {
        Self::default()
    }
}

impl ContentStore for MemoryStore {
    fn put(&mut self, blob: Vec<u8>) -> ContentId {
        let id = content_id(&blob);
        self.0.insert(id, blob);
        id
    }

    fn get(&self, id: ContentId) -> Option<Vec<u8>> {
        self.0.get(&id).cloned()
    }

    // Override the default (which would clone the whole blob just to test presence).
    fn contains(&self, id: ContentId) -> bool {
        self.0.contains_key(&id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const DT: f32 = 1.0 / 64.0;
    const LOCAL: PeerId = PeerId(1);

    /// A world with two locally-owned entities (one carrying `Contacts(5)`) and
    /// `Tick(42)`.
    fn build_world() -> World {
        let mut w = World::new();
        insert_sim(&mut w, LOCAL, DT);
        w.insert_resource(Tick(42));
        let a = spawn_owned(
            &mut w,
            LOCAL,
            Position { x: 1.0, y: 2.0 },
            Velocity { x: 0.5, y: -0.5 },
        );
        w.entity_mut(a).insert(Contacts(5));
        spawn_owned(
            &mut w,
            LOCAL,
            Position { x: -3.0, y: 4.0 },
            Velocity { x: 0.0, y: 1.0 },
        );
        w
    }

    fn owned_count(w: &World) -> usize {
        w.iter_entities()
            .filter(|e| e.get::<Owner>().is_some())
            .count()
    }

    #[test]
    fn round_trips_by_content_id() {
        let w = build_world();
        let (id, blob) = save_world(&w).expect("save");

        let mut store = MemoryStore::new();
        assert_eq!(store.put(blob.clone()), id);
        assert!(store.contains(id));

        let mut w2 = World::new();
        let loaded = load_world(&mut w2, &store.get(id).expect("get"), DT).expect("load");
        assert_eq!(loaded, id);

        // Fidelity: re-saving the reloaded world yields the SAME id.
        assert_eq!(save_world(&w2).expect("resave").0, id);
        // Restored resources + entity count.
        assert_eq!(w2.resource::<Tick>().0, 42);
        assert_eq!(w2.resource::<LocalPeer>().0, LOCAL);
        assert_eq!(owned_count(&w2), 2);
    }

    #[test]
    fn determinism_independent_of_spawn_order() {
        let mut a = World::new();
        insert_sim(&mut a, LOCAL, DT);
        a.insert_resource(Tick(7));
        spawn_owned(
            &mut a,
            LOCAL,
            Position { x: 1.0, y: 1.0 },
            Velocity { x: 0.0, y: 0.0 },
        );
        spawn_owned(
            &mut a,
            LOCAL,
            Position { x: 2.0, y: 2.0 },
            Velocity { x: 0.0, y: 0.0 },
        );

        let mut b = World::new();
        insert_sim(&mut b, LOCAL, DT);
        b.insert_resource(Tick(7));
        // Reversed spawn order, identical logical state.
        spawn_owned(
            &mut b,
            LOCAL,
            Position { x: 2.0, y: 2.0 },
            Velocity { x: 0.0, y: 0.0 },
        );
        spawn_owned(
            &mut b,
            LOCAL,
            Position { x: 1.0, y: 1.0 },
            Velocity { x: 0.0, y: 0.0 },
        );

        assert_eq!(save_world(&a).expect("a").0, save_world(&b).expect("b").0);
    }

    #[test]
    fn contacts_some_and_none_round_trip() {
        let w = build_world(); // one entity has Contacts(5), one has none
        let (_, blob) = save_world(&w).expect("save");
        let mut w2 = World::new();
        load_world(&mut w2, &blob, DT).expect("load");

        let contacts: Vec<u32> = w2
            .iter_entities()
            .filter_map(|e| e.get::<Contacts>().map(|c| c.0))
            .collect();
        assert_eq!(contacts, vec![5]); // exactly one, restored
        assert_eq!(owned_count(&w2), 2);
    }

    #[test]
    fn version_mismatch_is_rejected() {
        let w = build_world();
        let (_, mut blob) = save_world(&w).expect("save");
        blob[0] = 0xFF; // first byte is SaveBlob.version
        let mut w2 = World::new();
        assert!(matches!(
            load_world(&mut w2, &blob, DT),
            Err(SaveError::VersionMismatch { got: 0xFF })
        ));
    }

    #[test]
    fn content_mismatch_is_rejected_and_honest_blob_verifies() {
        let w = build_world();
        let (id, blob) = save_world(&w).expect("save");

        let mut tampered = blob.clone();
        let last = tampered.len() - 1;
        tampered[last] ^= 0x01;
        let mut w2 = World::new();
        assert!(matches!(
            load_world_verified(&mut w2, id, &tampered, DT),
            Err(SaveError::ContentMismatch { .. })
        ));

        // The honest blob verifies against its own id.
        let mut w3 = World::new();
        assert!(load_world_verified(&mut w3, id, &blob, DT).is_ok());
    }

    #[test]
    fn load_replaces_existing_populated_world() {
        // A saved 2-entity world (owner LOCAL, Tick 42).
        let (_, blob) = save_world(&build_world()).expect("save");

        // A DIFFERENT, already-populated target: 3 entities owned by PeerId(9), Tick 999.
        let mut w = World::new();
        insert_sim(&mut w, PeerId(9), DT);
        w.insert_resource(Tick(999));
        for i in 0..3 {
            spawn_owned(
                &mut w,
                PeerId(9),
                Position {
                    x: i as f32,
                    y: 0.0,
                },
                Velocity { x: 0.0, y: 0.0 },
            );
        }
        assert_eq!(owned_count(&w), 3);

        // Load REPLACES (not appends): only the saved 2 entities + saved resources remain.
        load_world(&mut w, &blob, DT).expect("load");
        assert_eq!(owned_count(&w), 2);
        assert_eq!(w.resource::<Tick>().0, 42);
        assert_eq!(w.resource::<LocalPeer>().0, LOCAL);
    }

    #[test]
    fn missing_resource_is_rejected() {
        let mut w = World::new();
        // No insert_sim ⇒ no Tick/LocalPeer.
        spawn_owned(
            &mut w,
            LOCAL,
            Position { x: 0.0, y: 0.0 },
            Velocity { x: 0.0, y: 0.0 },
        );
        assert!(matches!(save_world(&w), Err(SaveError::MissingResource(_))));
    }
}
